/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/resumes/validation-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validation Policy */
        get: operations["validation_policy_api_resumes_validation_policy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/extract/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pdf */
        post: operations["pdf_api_resumes_extract_pdf_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/extract/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Image */
        post: operations["image_api_resumes_extract_image_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/extract/docx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Docx */
        post: operations["docx_api_resumes_extract_docx_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/extract/txt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Txt */
        post: operations["txt_api_resumes_extract_txt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/extract/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Text */
        post: operations["text_api_resumes_extract_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Page */
        post: operations["start_page_api_reviews_page_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/flow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Flow */
        post: operations["start_flow_api_reviews_flow_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{run_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Result */
        get: operations["result_api_reviews__run_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_reviews__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_reviews__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{run_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry */
        post: operations["retry_api_reviews__run_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{run_id}/record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Record */
        get: operations["record_api_reviews__run_id__record_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Stored */
        post: operations["retry_stored_api_reviews_retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Release */
        delete: operations["release_api_reviews__run_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AiReviewOutput */
        AiReviewOutput: {
            /** Materialreviews */
            materialReviews: components["schemas"]["MaterialReviewDTO"][];
            /** Results */
            results: components["schemas"]["SuggestionDTO"][];
        };
        /** Body_docx_api_resumes_extract_docx_post */
        Body_docx_api_resumes_extract_docx_post: {
            /** File */
            file: string;
        };
        /** Body_image_api_resumes_extract_image_post */
        Body_image_api_resumes_extract_image_post: {
            /** File */
            file: string;
        };
        /** Body_pdf_api_resumes_extract_pdf_post */
        Body_pdf_api_resumes_extract_pdf_post: {
            /** File */
            file: string;
        };
        /** Body_txt_api_resumes_extract_txt_post */
        Body_txt_api_resumes_extract_txt_post: {
            /** File */
            file: string;
        };
        /** CancelAccepted */
        CancelAccepted: {
            /** Runid */
            runId: string;
            /** Cancelrequested */
            cancelRequested: boolean;
        };
        /** CompletedModules */
        CompletedModules: {
            spellCheck: components["schemas"]["ModuleResult_list_SpellDiagnostic__"];
            companyContextAnalysis?: components["schemas"]["ModuleResult_ContextAnalysis_"] | null;
            jobPostingAnalysis?: components["schemas"]["ModuleResult_ContextAnalysis_"] | null;
            finalReview: components["schemas"]["ModuleResult_AiReviewOutput_"];
        };
        /** ContextAnalysis */
        ContextAnalysis: {
            /** Summary */
            summary: string;
            /** Evidence */
            evidence: components["schemas"]["ContextEvidence"][];
        };
        /** ContextEvidence */
        ContextEvidence: {
            /** Sourceid */
            sourceId: string;
            /** Statement */
            statement: string;
        };
        /** DirectTextRequest */
        DirectTextRequest: {
            /** Text */
            text: string;
        };
        /** DocumentPage */
        DocumentPage: {
            /** Pagenumber */
            pageNumber: number;
            /** Blocks */
            blocks: components["schemas"]["PageBlock"][];
        };
        /** ExtractFlowDocumentResponse */
        ExtractFlowDocumentResponse: {
            document: components["schemas"]["FlowDocument"];
            /** Errors */
            errors: components["schemas"]["ModuleErrorDTO"][];
        };
        /** ExtractPageDocumentResponse */
        ExtractPageDocumentResponse: {
            document: components["schemas"]["PageDocument"];
            /** Errors */
            errors: components["schemas"]["ModuleErrorDTO"][];
        };
        /** FileSizeLimits */
        FileSizeLimits: {
            /** Pdf */
            pdf: number;
            /** Image */
            image: number;
            /** Docx */
            docx: number;
            /** Txt */
            txt: number;
        };
        /** FlowBlock */
        FlowBlock: {
            /** Blockid */
            blockId: string;
            /** Lines */
            lines: components["schemas"]["FlowLine"][];
        };
        /** FlowDocument */
        FlowDocument: {
            /** Text */
            text: string;
            /** Blocks */
            blocks: components["schemas"]["FlowBlock"][];
        };
        /** FlowLine */
        FlowLine: {
            /** Lineid */
            lineId: string;
            /** Text */
            text: string;
            /** Startoffset */
            startOffset: number;
            /** Endoffset */
            endOffset: number;
        };
        /** FlowReviewRequest */
        FlowReviewRequest: {
            document: components["schemas"]["FlowDocument"];
            /** Materials */
            materials?: components["schemas"]["ReferenceMaterial"][];
            previousReview?: components["schemas"]["PreviousReview"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MaterialEvidence */
        MaterialEvidence: {
            /** Sourceid */
            sourceId: string;
            /** Consideredpoint */
            consideredPoint: string;
        };
        /** MaterialReviewDTO */
        MaterialReviewDTO: {
            /** Sourceid */
            sourceId: string;
            materialType: components["schemas"]["MaterialType"];
            /**
             * Status
             * @enum {string}
             */
            status: "applied" | "notApplied";
            /** Reason */
            reason: string;
        };
        /**
         * MaterialType
         * @enum {string}
         */
        MaterialType: "company" | "jobPosting";
        /** ModuleErrorDTO */
        ModuleErrorDTO: {
            /** Modulekey */
            moduleKey: string;
            /** Inputsourceid */
            inputSourceId: string | null;
            /** Errorcode */
            errorCode: string;
            /** Usermessage */
            userMessage: string;
            /** Canretry */
            canRetry: boolean;
        };
        /** ModuleResult[AiReviewOutput] */
        ModuleResult_AiReviewOutput_: {
            /** Modulekey */
            moduleKey: string;
            output: components["schemas"]["AiReviewOutput"] | null;
            /** Errors */
            errors: components["schemas"]["ModuleErrorDTO"][];
        };
        /** ModuleResult[ContextAnalysis] */
        ModuleResult_ContextAnalysis_: {
            /** Modulekey */
            moduleKey: string;
            output: components["schemas"]["ContextAnalysis"] | null;
            /** Errors */
            errors: components["schemas"]["ModuleErrorDTO"][];
        };
        /** ModuleResult[list[SpellDiagnostic]] */
        ModuleResult_list_SpellDiagnostic__: {
            /** Modulekey */
            moduleKey: string;
            /** Output */
            output: components["schemas"]["SpellDiagnostic"][] | null;
            /** Errors */
            errors: components["schemas"]["ModuleErrorDTO"][];
        };
        /** NormalizedBBox */
        NormalizedBBox: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
        };
        /** PageBlock */
        PageBlock: {
            /** Blockid */
            blockId: string;
            bbox: components["schemas"]["NormalizedBBox"];
            /** Lines */
            lines: components["schemas"]["PageLine"][];
        };
        /** PageDocument */
        PageDocument: {
            /** Pages */
            pages: components["schemas"]["DocumentPage"][];
        };
        /** PageLine */
        PageLine: {
            /** Lineid */
            lineId: string;
            /** Text */
            text: string;
            bbox: components["schemas"]["NormalizedBBox"];
            /**
             * Textsource
             * @enum {string}
             */
            textSource: "embedded" | "ocr";
            /** Uncertainwords */
            uncertainWords: string[];
        };
        /** PageReviewRequest */
        PageReviewRequest: {
            document: components["schemas"]["PageDocument"];
            /** Materials */
            materials?: components["schemas"]["ReferenceMaterial"][];
            previousReview?: components["schemas"]["PreviousReview"] | null;
        };
        /** PreviousReview */
        PreviousReview: {
            /** Results */
            results: components["schemas"]["SuggestionDTO"][];
            /** Userfeedback */
            userFeedback?: string | null;
        };
        /** ReferenceMaterial */
        ReferenceMaterial: {
            /** Sourceid */
            sourceId: string;
            materialType: components["schemas"]["MaterialType"];
            /**
             * Inputtype
             * @enum {string}
             */
            inputType: "text" | "document" | "url";
            /** Content */
            content?: string | null;
            /** Url */
            url?: string | null;
        };
        /** ResumeValidationPolicy */
        ResumeValidationPolicy: {
            maximumFileSizeBytes: components["schemas"]["FileSizeLimits"];
            /** Maximumdirecttextcharacters */
            maximumDirectTextCharacters: number;
        };
        /** RetryRequest */
        RetryRequest: {
            /**
             * Modulekey
             * @enum {string}
             */
            moduleKey: "spellCheck" | "companyContextAnalysis" | "jobPostingAnalysis" | "finalReview";
        };
        /**
         * ReviewRecord
         * @description JSON record shared by storage and retry; contains no runtime objects.
         */
        ReviewRecord: {
            /** Runid */
            runId: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Document */
            document: components["schemas"]["PageDocument"] | components["schemas"]["FlowDocument"];
            /** Materials */
            materials: components["schemas"]["ReferenceMaterial"][];
            previousReview?: components["schemas"]["PreviousReview"] | null;
            moduleResults: components["schemas"]["CompletedModules"];
            response: components["schemas"]["ReviewResponse"];
        };
        /** ReviewResponse */
        ReviewResponse: {
            status: components["schemas"]["ReviewStatus"];
            /** Errors */
            errors: components["schemas"]["ModuleErrorDTO"][];
            /** Materialreviews */
            materialReviews: components["schemas"]["MaterialReviewDTO"][];
            /** Results */
            results: components["schemas"]["SuggestionDTO"][];
        };
        /**
         * ReviewStatus
         * @enum {string}
         */
        ReviewStatus: "success" | "partial" | "failed" | "cancelled";
        /** RunAccepted */
        RunAccepted: {
            /** Runid */
            runId: string;
        };
        /** SpellDiagnostic */
        SpellDiagnostic: {
            /** Lineid */
            lineId: string;
            /** Quote */
            quote: string;
            /** Replacement */
            replacement: string;
            /** Reason */
            reason: string;
        };
        /** StoredRetryRequest */
        StoredRetryRequest: {
            /**
             * Modulekey
             * @enum {string}
             */
            moduleKey: "spellCheck" | "companyContextAnalysis" | "jobPostingAnalysis" | "finalReview";
            record: components["schemas"]["ReviewRecord"];
        };
        /** SuggestionDTO */
        SuggestionDTO: {
            "\uC218\uC815\uD3EC\uC778\uD2B8\uC704\uCE58": components["schemas"]["SuggestionLocation"];
            /**
             * 수정성격
             * @enum {string}
             */
            "\uC218\uC815\uC131\uACA9": "맞춤법" | "사실성" | "근거" | "직무 관련성" | "회사 맥락" | "뉘앙스" | "가독성" | "기밀";
            /** 검토출처 */
            "\uAC80\uD1A0\uCD9C\uCC98": ("기본 검토" | "채용 공고" | "회사 자료")[];
            /** 검토자료근거 */
            "\uAC80\uD1A0\uC790\uB8CC\uADFC\uAC70": components["schemas"]["MaterialEvidence"][];
            /** 이유 및 제안 */
            "\uC774\uC720 \uBC0F \uC81C\uC548": string;
            /** 실제 수정 예시 */
            "\uC2E4\uC81C \uC218\uC815 \uC608\uC2DC": string;
        };
        /** SuggestionLocation */
        SuggestionLocation: {
            /** Lineids */
            lineIds: string[];
            /** Quote */
            quote: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    validation_policy_api_resumes_validation_policy_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeValidationPolicy"];
                };
            };
        };
    };
    pdf_api_resumes_extract_pdf_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_pdf_api_resumes_extract_pdf_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractPageDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    image_api_resumes_extract_image_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_image_api_resumes_extract_image_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractPageDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    docx_api_resumes_extract_docx_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_docx_api_resumes_extract_docx_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractFlowDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    txt_api_resumes_extract_txt_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_txt_api_resumes_extract_txt_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractFlowDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    text_api_resumes_extract_text_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DirectTextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractFlowDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_page_api_reviews_page_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PageReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_flow_api_reviews_flow_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlowReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    result_api_reviews__run_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_reviews__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_reviews__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_api_reviews__run_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_api_reviews__run_id__record_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_stored_api_reviews_retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoredRetryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    release_api_reviews__run_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
