import { act, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { expect, it, vi } from "vitest";
import { App } from "../../App";
import { createTestRouter } from "../../test/router";
import { IndexedDbWorkspaceRepository } from "../../infrastructure/workspace/IndexedDbWorkspaceRepository";
import type { AuthoringInput, WritingResult } from "../../domain/experience/entities";
import { MarkdownDocument, summaryMarkdown } from "./MarkdownDocument";

const policy = { maximumFileSizeBytes: { pdf: 1000, image: 1000, docx: 1000, txt: 1000 }, maximumDirectTextCharacters: 100_000 };
const result: WritingResult = { markdown: "# 로그인 요청 개선\n\n기간 확인 필요\n\n## 이력서용 요약\n\n- 중복 요청을 제거했다.\n\n## 상세 설명\n\n중복 요청이 발생하는 조건을 확인했다.\n\n## 근거\n\n작업 메모", summary: "- 중복 요청을 제거했다.", questions: ["어떤 조건에서 중복 요청이 발생했나요?"], sourceNotes: [] };

it("edits a generated portfolio draft, previews metadata and saves the experience", async () => {
  const store = new IndexedDbWorkspaceRepository(`experience-ui-${crypto.randomUUID()}`);
  const writeExperience = vi.fn().mockResolvedValue(result);
  const draftExperience = vi.fn().mockImplementation(async (input: AuthoringInput) => ({
    ...result, sourceNotes: input.sources.map((source, index) => ({ sourceId: source.id, verified: index === 0, text: "English source analysis should stay hidden" })),
  }));
  const experienceMetadata = vi.fn().mockResolvedValue({ metadata: "문제: 중복 요청. 해결: 요청 통합. 역량: 안정성 개선." });
  const confirm = vi.fn().mockReturnValue(false);
  const router = createTestRouter(["/experiences"]);
  const user = userEvent.setup();
  render(<App router={router} store={store} confirm={confirm} services={{ getValidationPolicy: async () => policy, writeExperience, draftExperience, experienceMetadata }} />);
  await user.click(await screen.findByRole("button", { name: "경험 남기기" }));
  expect(screen.queryByRole("dialog")).not.toBeInTheDocument();
  await user.type(screen.getByLabelText("제목"), "중복 요청 개선");
  await user.type(screen.getByLabelText("경험 Markdown 편집"), "중복 요청을 제거했다.");
  await user.click(screen.getByRole("tab", { name: "Preview" }));
  expect(screen.getByRole("tabpanel", { name: "Preview" })).toHaveTextContent("중복 요청을 제거했다.");
  expect(experienceMetadata).not.toHaveBeenCalled();
  expect(screen.getByRole("button", { name: "최종 저장" })).toBeDisabled();
  await user.keyboard("{ArrowLeft}");
  expect(screen.getByRole("tab", { name: "Markdown" })).toHaveFocus();
  expect(screen.getByLabelText("경험 Markdown 편집")).toHaveValue("중복 요청을 제거했다.");
  await user.type(screen.getByLabelText("관련 링크"), "https://example.com/work\nhttps://example.com/unavailable");
  await user.click(screen.getByRole("button", { name: "자료로 초안 작성" }));
  await waitFor(() => expect(screen.getByLabelText("경험 Markdown 편집")).toHaveValue(result.markdown));
  const sources = screen.getByRole("list", { name: "참고한 자료" });
  expect(within(sources).getAllByRole("listitem")).toHaveLength(2);
  expect(within(sources).getByText("https://example.com/work")).toBeInTheDocument();
  expect(within(sources).getByText("내용 확인 완료")).toBeInTheDocument();
  expect(within(sources).getByText("내용 확인 필요")).toBeInTheDocument();
  expect(screen.queryByText("English source analysis should stay hidden")).not.toBeInTheDocument();
  expect(screen.getByText(result.questions[0])).toBeInTheDocument();
  await user.type(screen.getByLabelText("경험 Markdown 편집"), "\n사용자가 보완한 근거");
  expect(screen.getByRole("button", { name: "최종 저장" })).toBeDisabled();
  await user.click(screen.getByRole("button", { name: "메타데이터 생성" }));
  await screen.findByLabelText("추천용 메타데이터");
  expect(experienceMetadata).toHaveBeenCalledWith(expect.objectContaining({ markdown: expect.stringContaining("사용자가 보완한 근거") }), expect.any(Function), expect.any(AbortSignal));
  fireEvent.change(screen.getByLabelText("추천용 메타데이터"), { target: { value: "" } });
  expect(screen.getByLabelText("추천용 메타데이터")).toHaveValue("");
  expect(screen.getByRole("button", { name: "최종 저장" })).toBeDisabled();
  fireEvent.change(screen.getByLabelText("추천용 메타데이터"), { target: { value: "검증된 역량: 운영 안정성 개선" } });
  await user.click(screen.getByRole("button", { name: "최종 저장" }));
  await screen.findByRole("heading", { name: "중복 요청 개선", level: 2 });
  await waitFor(() => expect(screen.getByRole("button", { name: "경험 남기기" })).toBeEnabled());
  expect(store.getSnapshot().experiences[0]).toMatchObject({ markdown: expect.stringContaining("사용자가 보완한 근거"), metadata: "검증된 역량: 운영 안정성 개선" });
  expect(writeExperience).not.toHaveBeenCalled();
});

it("keeps authoring edits on generation and save failures, regenerates stale metadata, and blocks navigation", async () => {
  const store = new IndexedDbWorkspaceRepository(`experience-failure-${crypto.randomUUID()}`);
  const experienceMetadata = vi.fn().mockRejectedValueOnce(new Error("분석 실패")).mockResolvedValue({ metadata: "문제와 해결 근거" });
  const draftExperience = vi.fn().mockRejectedValue(new Error("초안 작성 실패"));
  const router = createTestRouter(["/experiences"]);
  const user = userEvent.setup();
  render(<App router={router} store={store} confirm={() => false} services={{ getValidationPolicy: async () => policy, draftExperience, experienceMetadata }} />);
  await user.click(await screen.findByRole("button", { name: "경험 남기기" }));
  fireEvent.change(screen.getByLabelText("제목"), { target: { value: "작업 경험" } });
  fireEvent.change(screen.getByLabelText("경험 Markdown 편집"), { target: { value: "## 문제\n중복 요청" } });
  await user.click(screen.getByRole("button", { name: "자료로 초안 작성" }));
  await screen.findByRole("dialog", { name: "요청 오류" });
  await user.click(screen.getByRole("button", { name: "오류 팝업 닫기" }));
  expect(screen.getByLabelText("경험 Markdown 편집")).toHaveValue("## 문제\n중복 요청");
  await user.click(screen.getByRole("button", { name: "메타데이터 생성" }));
  await screen.findByRole("dialog", { name: "요청 오류" });
  await user.click(screen.getByRole("button", { name: "오류 팝업 닫기" }));
  expect(screen.getByRole("button", { name: "최종 저장" })).toBeDisabled();
  expect(screen.getByLabelText("경험 Markdown 편집")).toHaveValue("## 문제\n중복 요청");
  await user.click(screen.getByRole("button", { name: "메타데이터 생성" }));
  await waitFor(() => expect(screen.getByRole("button", { name: "최종 저장" })).toBeEnabled());
  await user.click(screen.getByRole("tab", { name: "Markdown" }));
  await user.type(screen.getByLabelText("경험 Markdown 편집"), "\n재현 조건 추가");
  expect(screen.getByRole("button", { name: "최종 저장" })).toBeDisabled();
  await user.click(screen.getByRole("button", { name: "메타데이터 생성" }));
  await waitFor(() => expect(screen.getByRole("button", { name: "최종 저장" })).toBeEnabled());
  expect(experienceMetadata).toHaveBeenLastCalledWith(expect.objectContaining({ markdown: "## 문제\n중복 요청\n재현 조건 추가" }), expect.any(Function), expect.any(AbortSignal));
  fireEvent.change(screen.getByLabelText("제목"), { target: { value: "수정한 경험 제목" } });
  expect(screen.getByRole("button", { name: "최종 저장" })).toBeDisabled();
  await user.click(screen.getByRole("button", { name: "메타데이터 생성" }));
  await waitFor(() => expect(screen.getByRole("button", { name: "최종 저장" })).toBeEnabled());
  vi.spyOn(store, "saveExperience").mockRejectedValueOnce(new Error("저장 공간 부족"));
  await user.click(screen.getByRole("button", { name: "최종 저장" }));
  await screen.findByRole("dialog", { name: "요청 오류" });
  await user.click(screen.getByRole("button", { name: "오류 팝업 닫기" }));
  expect(screen.getByLabelText("추천용 메타데이터")).toHaveValue("문제와 해결 근거");
  await act(() => router.navigate("/contexts"));
  expect(router.state.location.pathname).toBe("/experiences");
  expect(screen.getByLabelText("경험 Markdown 편집")).toHaveValue("## 문제\n중복 요청\n재현 조건 추가");
  await user.click(screen.getByRole("button", { name: "최종 저장" }));
  await screen.findByRole("heading", { name: "수정한 경험 제목", level: 2 });
  expect(store.getSnapshot().experiences).toHaveLength(1);
});

it("blocks direct image attachments before AI submission without losing the Markdown draft", async () => {
  const store = new IndexedDbWorkspaceRepository(`experience-image-${crypto.randomUUID()}`);
  const draftExperience = vi.fn();
  const user = userEvent.setup({ applyAccept: false });
  render(<App router={createTestRouter(["/experiences"])} store={store} services={{ getValidationPolicy: async () => policy, draftExperience }} />);
  await user.click(await screen.findByRole("button", { name: "경험 남기기" }));
  fireEvent.change(screen.getByLabelText("경험 Markdown 편집"), { target: { value: "작성 중인 경험" } });
  await user.upload(screen.getByLabelText("경험 파일 첨부"), new File(["image"], "evidence.png", { type: "image/png" }));
  await user.click(screen.getByRole("button", { name: "자료로 초안 작성" }));
  await screen.findByRole("dialog", { name: "요청 오류" });
  expect(draftExperience).not.toHaveBeenCalled();
  await user.click(screen.getByRole("button", { name: "오류 팝업 닫기" }));
  expect(screen.getByLabelText("경험 Markdown 편집")).toHaveValue("작성 중인 경험");
  await user.click(screen.getByRole("button", { name: "evidence.png 첨부 취소" }));
  expect(screen.queryByText("evidence.png")).not.toBeInTheDocument();
});

it("renders Markdown tables safely and copies the edited summary instead of stale generated text", () => {
  render(<MarkdownDocument markdown={'![외부 이미지](https://example.com/image.png)\n\n![상대 경로](/private.png)\n\n![위험한 이미지](javascript:alert)\n\n![로컬 이미지](data:image/png;base64,abcd)\n\n# 경험\n\n<script>alert(1)</script>\n\n[unsafe](javascript:alert(1))\n\n| 시도 | 결과 |\n| --- | --- |\n| 요청 통합 | 확인 중 |'} />);
  expect(screen.getByRole("table")).toBeInTheDocument();
  expect(screen.getAllByRole("img")).toHaveLength(1);
  expect(screen.getByRole("img", { name: "외부 이미지" })).toHaveAttribute("src", "https://example.com/image.png");
  expect(screen.getByRole("img", { name: "외부 이미지" })).toHaveAttribute("referrerpolicy", "no-referrer");
  expect(document.querySelector("script")).toBeNull();
  expect(screen.getByText("unsafe")).not.toHaveAttribute("href", expect.stringContaining("javascript:"));
  expect(summaryMarkdown(result.markdown.replace("- 중복 요청을 제거했다.", "- 사용자가 고친 요약"))).toBe("- 사용자가 고친 요약");
  expect(summaryMarkdown("# 요약 없는 문서")).toBe("");
});

it("shows live progress in only the generating area and restores inputs after failure", async () => {
  const store = new IndexedDbWorkspaceRepository(`experience-progress-${crypto.randomUUID()}`);
  let report: (message: string) => void = () => {};
  let finish: (value: WritingResult) => void = () => {};
  let fail: (reason: Error) => void = () => {};
  const draftExperience = vi.fn((_input, onProgress) => {
    report = onProgress;
    return new Promise<WritingResult>(resolve => { finish = resolve; });
  });
  const experienceMetadata = vi.fn((_input, onProgress) => {
    report = onProgress;
    return new Promise<{ metadata: string }>((_resolve, reject) => { fail = reject; });
  });
  const user = userEvent.setup();
  render(<App router={createTestRouter(["/experiences"])} store={store} services={{ getValidationPolicy: async () => policy, draftExperience, experienceMetadata }} />);
  await user.click(await screen.findByRole("button", { name: "경험 남기기" }));
  fireEvent.change(screen.getByLabelText("경험 Markdown 편집"), { target: { value: "작성 중인 본문" } });
  await user.click(screen.getByRole("button", { name: "자료로 초안 작성" }));
  const panel = screen.getByRole("tabpanel", { name: "Markdown" });
  expect(within(panel).getByRole("status")).toHaveTextContent("첨부 자료를 준비하고 있습니다.");
  expect(panel.querySelector('.experience-generation-skeleton[aria-hidden="true"]')).not.toBeNull();
  expect(screen.queryByLabelText("경험 Markdown 편집")).not.toBeInTheDocument();
  act(() => report("링크 확인 후 경험 초안을 작성하고 있습니다."));
  expect(within(panel).getByRole("status")).toHaveTextContent("링크 확인 후 경험 초안을 작성하고 있습니다.");
  await act(async () => finish(result));
  expect(screen.getByLabelText("경험 Markdown 편집")).toHaveValue(result.markdown);
  expect(panel.querySelector(".experience-generation-skeleton")).toBeNull();
  await user.click(screen.getByRole("button", { name: "메타데이터 생성" }));
  act(() => report("문제와 해결의 근거를 정리하고 있습니다."));
  expect(screen.getByText("문제와 해결의 근거를 정리하고 있습니다.").closest(".experience-authoring-metadata")).not.toBeNull();
  expect(screen.getByLabelText("경험 Markdown 편집")).toHaveValue(result.markdown);
  expect(screen.getByLabelText("경험 Markdown 편집")).toBeDisabled();
  expect(document.querySelector(".is-metadata .experience-generation-skeleton")).not.toBeNull();
  await act(async () => fail(new Error("연결이 끊겼습니다.")));
  await screen.findByRole("dialog", { name: "요청 오류" });
  expect(document.querySelector(".experience-generation-skeleton")).toBeNull();
  await user.click(screen.getByRole("button", { name: "오류 팝업 닫기" }));
  expect(screen.getByLabelText("경험 Markdown 편집")).toHaveValue(result.markdown);
  expect(screen.getByRole("button", { name: "메타데이터 생성" })).toBeEnabled();
});
