/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/resumes/validation-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validation Policy */
        get: operations["validation_policy_api_resumes_validation_policy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/extract/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pdf */
        post: operations["pdf_api_resumes_extract_pdf_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/extract/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Image */
        post: operations["image_api_resumes_extract_image_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/extract/docx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Docx */
        post: operations["docx_api_resumes_extract_docx_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/extract/txt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Txt */
        post: operations["txt_api_resumes_extract_txt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resumes/extract/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Text */
        post: operations["text_api_resumes_extract_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Page */
        post: operations["start_page_api_reviews_page_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/flow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Flow */
        post: operations["start_flow_api_reviews_flow_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{run_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Result */
        get: operations["result_api_reviews__run_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_reviews__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_reviews__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{run_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry */
        post: operations["retry_api_reviews__run_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{run_id}/record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Record */
        get: operations["record_api_reviews__run_id__record_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Stored */
        post: operations["retry_stored_api_reviews_retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Release */
        delete: operations["release_api_reviews__run_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/materials/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview */
        post: operations["preview_api_materials_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiences/write": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Write Experience */
        post: operations["write_experience_api_experiences_write_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiences/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Draft Experience */
        post: operations["draft_experience_api_experiences_draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiences/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Metadata */
        post: operations["generate_metadata_api_experiences_metadata_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Account */
        get: operations["account_api_account_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account/openai-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Key */
        put: operations["save_key_api_account_openai_key_put"];
        post?: never;
        /** Delete Key */
        delete: operations["delete_key_api_account_openai_key_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Load Workspace */
        get: operations["load_workspace_api_workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Workspace Command */
        post: operations["workspace_command_api_workspace_commands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Local Workspace */
        post: operations["import_local_workspace_api_workspace_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/import/{import_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Import Status */
        get: operations["import_status_api_workspace_import__import_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload File */
        post: operations["upload_file_api_files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download File */
        get: operations["download_file_api_files__file_id__get"];
        put?: never;
        post?: never;
        /** Delete Unused File */
        delete: operations["delete_unused_file_api_files__file_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backup Status */
        get: operations["backup_status_api_operations_backup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountResponse */
        AccountResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Mode */
            mode: string;
            /** Isoperator */
            isOperator: boolean;
            /** Hasopenaikey */
            hasOpenAiKey: boolean;
            /** Maskedopenaikey */
            maskedOpenAiKey: string | null;
        };
        /** AiReviewOutput */
        AiReviewOutput: {
            /** Experiencerecommendations */
            experienceRecommendations?: components["schemas"]["ExperienceRecommendation"][];
            /** Resolutionchecks */
            resolutionChecks?: components["schemas"]["ResolutionCheck"][];
            /** Materialreviews */
            materialReviews: components["schemas"]["MaterialReviewDTO"][];
            /** Results */
            results: components["schemas"]["SuggestionDTO"][];
        };
        /** AuthoringInput */
        AuthoringInput: {
            /** Title */
            title: string;
            /** Period */
            period: string;
            /**
             * Markdown
             * @default
             */
            markdown: string;
            /** Sources */
            sources?: components["schemas"]["Source"][];
            /**
             * Usetemplate
             * @default true
             */
            useTemplate: boolean;
        };
        /** BackupStatus */
        BackupStatus: {
            /** Lastattemptat */
            lastAttemptAt: string | null;
            /** Lastsuccessat */
            lastSuccessAt: string | null;
            /** Error */
            error: ("BACKUP_NOT_RUN" | "BACKUP_STATUS_UNAVAILABLE" | "BACKUP_OR_RETENTION_FAILED") | null;
        };
        /** Body_docx_api_resumes_extract_docx_post */
        Body_docx_api_resumes_extract_docx_post: {
            /** File */
            file: string;
        };
        /** Body_image_api_resumes_extract_image_post */
        Body_image_api_resumes_extract_image_post: {
            /** File */
            file: string;
        };
        /** Body_pdf_api_resumes_extract_pdf_post */
        Body_pdf_api_resumes_extract_pdf_post: {
            /** File */
            file: string;
        };
        /** Body_txt_api_resumes_extract_txt_post */
        Body_txt_api_resumes_extract_txt_post: {
            /** File */
            file: string;
        };
        /** Body_upload_file_api_files_post */
        Body_upload_file_api_files_post: {
            /** File */
            file: string;
        };
        /** CancelAccepted */
        CancelAccepted: {
            /** Runid */
            runId: string;
            /** Cancelrequested */
            cancelRequested: boolean;
        };
        /** Command */
        Command: {
            /**
             * Operation
             * @enum {string}
             */
            operation: "createContext" | "addResumeVersion" | "saveMaterial" | "attachMaterial" | "detachMaterial" | "deleteMaterial" | "deleteContext" | "saveExperience" | "saveExperienceDocument" | "deleteExperienceDocument" | "setSuggestionFeedback" | "saveReviewFeedback" | "setContextExperiences" | "prepareReview" | "prepareRetry" | "restoreRecord" | "clearActiveRun" | "registerRun" | "completeReview";
            /** Args */
            args: unknown[];
        };
        /** CompletedModules */
        CompletedModules: {
            spellCheck: components["schemas"]["ModuleResult_list_SpellDiagnostic__"];
            companyContextAnalysis?: components["schemas"]["ModuleResult_ContextAnalysis_"] | null;
            jobPostingAnalysis?: components["schemas"]["ModuleResult_ContextAnalysis_"] | null;
            finalReview: components["schemas"]["ModuleResult_AiReviewOutput_"];
        };
        /** Context */
        Context: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Createdat */
            createdAt: string;
            /** Latestversionid */
            latestVersionId: string;
            /** Latestreviewid */
            latestReviewId?: string | null;
            /** Lastattemptid */
            lastAttemptId?: string | null;
            /** Selectedexperienceids */
            selectedExperienceIds?: string[];
            /** Userfeedback */
            userFeedback: string;
        };
        /** ContextAnalysis */
        ContextAnalysis: {
            /** Summary */
            summary: string;
            /** Evidence */
            evidence: components["schemas"]["ContextEvidence"][];
            /** Materialsummaries */
            materialSummaries?: components["schemas"]["MaterialSummary"][];
        };
        /** ContextEvidence */
        ContextEvidence: {
            /** Sourceid */
            sourceId: string;
            /** Statement */
            statement: string;
        };
        /** ContextMaterial */
        ContextMaterial: {
            /** Id */
            id: string;
            /** Contextid */
            contextId: string;
            /** Materialid */
            materialId: string;
        };
        /** ContextRefs */
        ContextRefs: {
            /** Contextid */
            contextId: string;
            /** Resumeversionid */
            resumeVersionId: string;
            /** Materialversions */
            materialVersions?: {
                [key: string]: string;
            };
            /** Previousreviewid */
            previousReviewId?: string | null;
            /** Feedback */
            feedback?: components["schemas"]["FeedbackReference"][];
            /** Resolved */
            resolved?: components["schemas"]["ResolvedMemory"][];
            /** Userfeedback */
            userFeedback?: string | null;
            /** Experiences */
            experiences?: components["schemas"]["ExperienceCandidate"][];
            /** Selectedexperienceids */
            selectedExperienceIds?: string[];
        };
        /** DirectTextRequest */
        DirectTextRequest: {
            /** Text */
            text: string;
        };
        /** DocumentPage */
        DocumentPage: {
            /** Pagenumber */
            pageNumber: number;
            /** Blocks */
            blocks: components["schemas"]["PageBlock"][];
        };
        /** Experience */
        Experience: {
            /** Title */
            title: string;
            /** Period */
            period: string;
            /** Sources */
            sources: components["schemas"]["ExperienceSource"][];
            /** Markdown */
            markdown?: string | null;
            /** Metadata */
            metadata?: string | null;
            /**
             * Talkingpoints
             * @default
             */
            talkingPoints: string;
            /** Interviewquestions */
            interviewQuestions?: components["schemas"]["InterviewQuestion"][];
            /** Id */
            id: string;
            /** Revision */
            revision: number;
            /** Createdat */
            createdAt: string;
            /** Updatedat */
            updatedAt: string;
        };
        /** ExperienceCandidate */
        ExperienceCandidate: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Period */
            period: string;
            /** Revision */
            revision: number;
            /** Markdown */
            markdown: string;
            /** Metadata */
            metadata: string;
        };
        /** ExperienceInput */
        ExperienceInput: {
            /** Title */
            title: string;
            /** Period */
            period: string;
            /**
             * Markdown
             * @default
             */
            markdown: string;
            /** Sources */
            sources?: components["schemas"]["Source"][];
            /** Id */
            id: string;
            /** Revision */
            revision: number;
            /**
             * Metadata
             * @default
             */
            metadata: string;
        };
        /** ExperienceRecommendation */
        ExperienceRecommendation: {
            /** Experienceid */
            experienceId: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "include" | "suggest" | "omit";
            /** Reason */
            reason: string;
            /** Jobevidence */
            jobEvidence: components["schemas"]["MaterialEvidence"][];
            /** Resumebullets */
            resumeBullets: string[];
            /** Placement */
            placement: string;
        };
        /** ExperienceSnapshot */
        ExperienceSnapshot: {
            /** Title */
            title: string;
            /** Period */
            period: string;
            /** Sources */
            sources: components["schemas"]["ExperienceSource"][];
            /** Markdown */
            markdown?: string | null;
            /** Metadata */
            metadata?: string | null;
            /**
             * Talkingpoints
             * @default
             */
            talkingPoints: string;
            /** Interviewquestions */
            interviewQuestions?: components["schemas"]["InterviewQuestion"][];
            /** Id */
            id: string;
            /** Revision */
            revision: number;
        };
        /** ExperienceSource */
        ExperienceSource: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "note" | "link" | "file";
            /** Name */
            name: string;
            /** Text */
            text: string;
            /** Url */
            url?: string | null;
            original?: components["schemas"]["FileReference"] | null;
            /** Createdat */
            createdAt: string;
        };
        /** ExtractFlowDocumentResponse */
        ExtractFlowDocumentResponse: {
            document: components["schemas"]["FlowDocument"];
            /** Errors */
            errors: components["schemas"]["ModuleErrorDTO"][];
        };
        /** ExtractPageDocumentResponse */
        ExtractPageDocumentResponse: {
            document: components["schemas"]["PageDocument"];
            /** Errors */
            errors: components["schemas"]["ModuleErrorDTO"][];
        };
        /** ExtractionIssue */
        ExtractionIssue: {
            /**
             * Stage
             * @enum {string}
             */
            stage: "assessment" | "recovery";
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Pagenumber */
            pageNumber?: number | null;
            /** Lineids */
            lineIds?: string[];
            bbox?: components["schemas"]["NormalizedBBox"] | null;
            /**
             * Recovered
             * @default false
             */
            recovered: boolean;
        };
        /** ExtractionReport */
        ExtractionReport: {
            /**
             * Status
             * @enum {string}
             */
            status: "complete" | "recovered" | "needs_review";
            /** Issues */
            issues?: components["schemas"]["ExtractionIssue"][];
            /**
             * Confirmed
             * @default false
             */
            confirmed: boolean;
        };
        /** FeedbackReference */
        FeedbackReference: {
            /** Id */
            id: string;
            /** Contextid */
            contextId: string;
            /** Reviewid */
            reviewId: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "resolve" | "skip";
            /** Rating */
            rating: ("up" | "down") | null;
        };
        /** FileReference */
        FileReference: {
            /** Fileid */
            fileId: string;
        };
        /** FileSizeLimits */
        FileSizeLimits: {
            /** Pdf */
            pdf: number;
            /** Image */
            image: number;
            /** Docx */
            docx: number;
            /** Txt */
            txt: number;
        };
        /** FlowBlock */
        FlowBlock: {
            /** Blockid */
            blockId: string;
            /** Lines */
            lines: components["schemas"]["FlowLine"][];
        };
        /** FlowDocument */
        FlowDocument: {
            /** Text */
            text: string;
            /** Blocks */
            blocks: components["schemas"]["FlowBlock"][];
            extraction?: components["schemas"]["ExtractionReport"] | null;
        };
        /** FlowLine */
        FlowLine: {
            /** Lineid */
            lineId: string;
            /** Text */
            text: string;
            /** Startoffset */
            startOffset: number;
            /** Endoffset */
            endOffset: number;
        };
        /** FlowReviewRequest */
        FlowReviewRequest: {
            document: components["schemas"]["FlowDocument"];
            /** Materials */
            materials?: components["schemas"]["ReferenceMaterial"][];
            previousReview?: components["schemas"]["PreviousReview"] | null;
            reviewContext?: components["schemas"]["ReviewContext"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportRequest */
        ImportRequest: {
            /** Importid */
            importId: string;
            workspace: components["schemas"]["ImportedWorkspace"];
        };
        /** ImportedWorkspace */
        ImportedWorkspace: {
            /** Contexts */
            contexts: components["schemas"]["Context"][];
            /** Resumeversions */
            resumeVersions: components["schemas"]["ResumeVersion"][];
            /** Materials */
            materials: components["schemas"]["Material"][];
            /** Materialversions */
            materialVersions: components["schemas"]["MaterialVersion"][];
            /** Contextmaterials */
            contextMaterials: components["schemas"]["ContextMaterial"][];
            /** Reviews */
            reviews: components["schemas"]["Review"][];
            /** Suggestions */
            suggestions: components["schemas"]["SuggestionEntry"][];
            /** Reviewmaterials */
            reviewMaterials: components["schemas"]["ReviewMaterial"][];
            /** Experiences */
            experiences: components["schemas"]["Experience"][];
            /** Experiencedocuments */
            experienceDocuments: components["schemas"]["SavedExperienceDocument"][];
        };
        /** InterviewQuestion */
        InterviewQuestion: {
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /** Evidence */
            evidence: string;
        };
        /** KeyInput */
        KeyInput: {
            /**
             * Apikey
             * Format: password
             */
            apiKey: string;
        };
        /** Material */
        Material: {
            /** Id */
            id: string;
            /**
             * Materialtype
             * @enum {string}
             */
            materialType: "company" | "jobPosting";
            /** Currentversionid */
            currentVersionId: string | null;
            /** Deleted */
            deleted: boolean;
            draft?: components["schemas"]["MaterialDraft"] | null;
        };
        /** MaterialDraft */
        MaterialDraft: {
            /** Title */
            title: string;
            /**
             * Materialtype
             * @enum {string}
             */
            materialType: "company" | "jobPosting";
            /** Content */
            content: string;
            /** Source */
            source: string;
            /** Original */
            original?: components["schemas"]["FileReference"] | string | null;
        };
        /** MaterialEvidence */
        MaterialEvidence: {
            /** Sourceid */
            sourceId: string;
            /** Consideredpoint */
            consideredPoint: string;
        };
        /** MaterialInput */
        MaterialInput: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Content */
            content: string;
            /**
             * Materialtype
             * @enum {string}
             */
            materialType: "company" | "jobPosting";
        };
        /** MaterialPreviewRequest */
        MaterialPreviewRequest: {
            materialType: components["schemas"]["MaterialType"];
            /** Content */
            content: string;
        };
        /** MaterialPreviewResponse */
        MaterialPreviewResponse: {
            /** Content */
            content: string;
            /** Sources */
            sources: string[];
        };
        /** MaterialReviewDTO */
        MaterialReviewDTO: {
            /** Sourceid */
            sourceId: string;
            materialType: components["schemas"]["MaterialType"];
            /**
             * Status
             * @enum {string}
             */
            status: "applied" | "notApplied";
            /** Reason */
            reason: string;
        };
        /** MaterialSummary */
        MaterialSummary: {
            /** Sourceid */
            sourceId: string;
            /** Summary */
            summary: string;
        };
        /**
         * MaterialType
         * @enum {string}
         */
        MaterialType: "company" | "jobPosting";
        /** MaterialVersion */
        MaterialVersion: {
            /** Title */
            title: string;
            /**
             * Materialtype
             * @enum {string}
             */
            materialType: "company" | "jobPosting";
            /** Content */
            content: string;
            /** Source */
            source: string;
            /** Original */
            original?: components["schemas"]["FileReference"] | string | null;
            /** Id */
            id: string;
            /** Materialid */
            materialId: string;
            /** Version */
            version: number;
            /** Createdat */
            createdAt: string;
            /** Legacyurl */
            legacyUrl?: string | null;
        };
        /** MetadataInput */
        MetadataInput: {
            /** Title */
            title: string;
            /** Period */
            period: string;
            /** Markdown */
            markdown: string;
        };
        /** MetadataResult */
        MetadataResult: {
            /** Metadata */
            metadata: string;
            /**
             * Talkingpoints
             * @default
             */
            talkingPoints: string;
            /** Interviewquestions */
            interviewQuestions?: components["schemas"]["InterviewQuestion"][];
        };
        /** ModuleErrorDTO */
        ModuleErrorDTO: {
            /** Modulekey */
            moduleKey: string;
            /** Inputsourceid */
            inputSourceId: string | null;
            /** Errorcode */
            errorCode: string;
            /** Usermessage */
            userMessage: string;
            /** Canretry */
            canRetry: boolean;
        };
        /** ModuleResult[AiReviewOutput] */
        ModuleResult_AiReviewOutput_: {
            /** Modulekey */
            moduleKey: string;
            output: components["schemas"]["AiReviewOutput"] | null;
            /** Errors */
            errors: components["schemas"]["ModuleErrorDTO"][];
        };
        /** ModuleResult[ContextAnalysis] */
        ModuleResult_ContextAnalysis_: {
            /** Modulekey */
            moduleKey: string;
            output: components["schemas"]["ContextAnalysis"] | null;
            /** Errors */
            errors: components["schemas"]["ModuleErrorDTO"][];
        };
        /** ModuleResult[list[SpellDiagnostic]] */
        ModuleResult_list_SpellDiagnostic__: {
            /** Modulekey */
            moduleKey: string;
            /** Output */
            output: components["schemas"]["SpellDiagnostic"][] | null;
            /** Errors */
            errors: components["schemas"]["ModuleErrorDTO"][];
        };
        /** NormalizedBBox */
        NormalizedBBox: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
        };
        /** PageBlock */
        PageBlock: {
            /** Blockid */
            blockId: string;
            bbox: components["schemas"]["NormalizedBBox"];
            /** Lines */
            lines: components["schemas"]["PageLine"][];
        };
        /** PageDocument */
        PageDocument: {
            /** Pages */
            pages: components["schemas"]["DocumentPage"][];
            extraction?: components["schemas"]["ExtractionReport"] | null;
        };
        /** PageLine */
        PageLine: {
            /** Lineid */
            lineId: string;
            /** Text */
            text: string;
            bbox: components["schemas"]["NormalizedBBox"];
            /**
             * Textsource
             * @enum {string}
             */
            textSource: "embedded" | "ocr";
            /** Uncertainwords */
            uncertainWords: string[];
        };
        /** PageReviewRequest */
        PageReviewRequest: {
            document: components["schemas"]["PageDocument"];
            /** Materials */
            materials?: components["schemas"]["ReferenceMaterial"][];
            previousReview?: components["schemas"]["PreviousReview"] | null;
            reviewContext?: components["schemas"]["ReviewContext"] | null;
        };
        /** PreviousReview */
        PreviousReview: {
            /** Results */
            results: components["schemas"]["SuggestionDTO"][];
            /** Userfeedback */
            userFeedback?: string | null;
        };
        /** ReferenceMaterial */
        ReferenceMaterial: {
            /** Sourceid */
            sourceId: string;
            materialType: components["schemas"]["MaterialType"];
            /**
             * Inputtype
             * @enum {string}
             */
            inputType: "text" | "document" | "url";
            /** Content */
            content?: string | null;
            /** Url */
            url?: string | null;
        };
        /** ResolutionCheck */
        ResolutionCheck: {
            /** Suggestionid */
            suggestionId: string;
            /**
             * Status
             * @enum {string}
             */
            status: "resolved" | "notApplied" | "uncertain";
            /** Reason */
            reason: string;
            evidence?: components["schemas"]["SuggestionLocation"] | null;
        };
        /** ResolvedMemory */
        ResolvedMemory: {
            /** Suggestionid */
            suggestionId: string;
            /** Quote */
            quote: string;
            /** Reason */
            reason: string;
        };
        /** ResumeInput */
        ResumeInput: {
            /** Id */
            id: string;
            /** Text */
            text: string;
        };
        /** ResumeValidationPolicy */
        ResumeValidationPolicy: {
            maximumFileSizeBytes: components["schemas"]["FileSizeLimits"];
            /** Maximumdirecttextcharacters */
            maximumDirectTextCharacters: number;
        };
        /** ResumeVersion */
        ResumeVersion: {
            /** Id */
            id: string;
            /** Contextid */
            contextId: string;
            /** Version */
            version: number;
            /** Createdat */
            createdAt: string;
            /**
             * Inputtype
             * @enum {string}
             */
            inputType: "file" | "text";
            /** Displayname */
            displayName: string;
            /** Original */
            original?: components["schemas"]["FileReference"] | string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "extracting" | "ready" | "failed";
            /** Documentkind */
            documentKind?: ("page" | "flow") | null;
            /** Document */
            document?: components["schemas"]["PageDocument"] | components["schemas"]["FlowDocument"] | null;
        };
        /** RetryRequest */
        RetryRequest: {
            /**
             * Modulekey
             * @enum {string}
             */
            moduleKey: "spellCheck" | "companyContextAnalysis" | "jobPostingAnalysis" | "finalReview";
        };
        /** Review */
        Review: {
            /** Id */
            id: string;
            /** Contextid */
            contextId: string;
            /** Resumeversionid */
            resumeVersionId: string | null;
            /** Createdat */
            createdAt: string;
            input: components["schemas"]["ContextRefs"];
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "partial" | "failed" | "cancelled";
            /** Errors */
            errors: components["schemas"]["ModuleErrorDTO"][];
            /** Materialreviews */
            materialReviews: components["schemas"]["MaterialReviewDTO"][];
            /** Resolutionchecks */
            resolutionChecks: components["schemas"]["ResolutionCheck"][];
            /** Resultids */
            resultIds: string[];
            /** Suggestionids */
            suggestionIds: string[];
            /** Experiencerecommendations */
            experienceRecommendations?: components["schemas"]["ExperienceRecommendation"][];
            modules: components["schemas"]["ReviewModules"];
            /** Finalerrors */
            finalErrors: components["schemas"]["ModuleErrorDTO"][];
            /** Finalfailed */
            finalFailed: boolean;
        };
        /** ReviewContext */
        ReviewContext: {
            /** Contextid */
            contextId: string;
            /** Resumeversionid */
            resumeVersionId: string;
            /** Materialversions */
            materialVersions?: {
                [key: string]: string;
            };
            /** Previousreviewid */
            previousReviewId?: string | null;
            /** Feedback */
            feedback?: components["schemas"]["SuggestionFeedback"][];
            /** Resolved */
            resolved?: components["schemas"]["ResolvedMemory"][];
            /** Userfeedback */
            userFeedback?: string | null;
            /** Experiences */
            experiences?: components["schemas"]["ExperienceCandidate"][];
            /** Selectedexperienceids */
            selectedExperienceIds?: string[];
        };
        /** ReviewMaterial */
        ReviewMaterial: {
            /** Id */
            id: string;
            /** Reviewid */
            reviewId: string;
            /** Materialversionid */
            materialVersionId: string;
        };
        /** ReviewModules */
        ReviewModules: {
            spellCheck: components["schemas"]["ModuleResult_list_SpellDiagnostic__"];
            companyContextAnalysis?: components["schemas"]["ModuleResult_ContextAnalysis_"] | null;
            jobPostingAnalysis?: components["schemas"]["ModuleResult_ContextAnalysis_"] | null;
        };
        /**
         * ReviewRecord
         * @description JSON record shared by storage and retry; contains no runtime objects.
         */
        ReviewRecord: {
            /** Runid */
            runId: string;
            reviewContext?: components["schemas"]["ReviewContext"] | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Document */
            document: components["schemas"]["PageDocument"] | components["schemas"]["FlowDocument"];
            /** Materials */
            materials: components["schemas"]["ReferenceMaterial"][];
            previousReview?: components["schemas"]["PreviousReview"] | null;
            moduleResults: components["schemas"]["CompletedModules"];
            response: components["schemas"]["ReviewResponse"];
        };
        /** ReviewResponse */
        ReviewResponse: {
            /** Experiencerecommendations */
            experienceRecommendations?: components["schemas"]["ExperienceRecommendation"][];
            /** Resolutionchecks */
            resolutionChecks?: components["schemas"]["ResolutionCheck"][];
            status: components["schemas"]["ReviewStatus"];
            /** Errors */
            errors: components["schemas"]["ModuleErrorDTO"][];
            /** Materialreviews */
            materialReviews: components["schemas"]["MaterialReviewDTO"][];
            /** Results */
            results: components["schemas"]["SuggestionDTO"][];
        };
        /**
         * ReviewStatus
         * @enum {string}
         */
        ReviewStatus: "success" | "partial" | "failed" | "cancelled";
        /** RunAccepted */
        RunAccepted: {
            /** Runid */
            runId: string;
        };
        /** SavedExperienceDocument */
        SavedExperienceDocument: {
            /** Id */
            id: string;
            /** Contextid */
            contextId: string;
            /** Experienceid */
            experienceId: string;
            input: components["schemas"]["app__workspace__models__WritingInput"];
            /** Markdown */
            markdown: string;
            /** Summary */
            summary: string;
            /** Questions */
            questions: string[];
            /** Sourcenotes */
            sourceNotes: components["schemas"]["SourceNote-Input"][];
            /** Revision */
            revision: number;
            /** Createdat */
            createdAt: string;
            /** Updatedat */
            updatedAt: string;
        };
        /** Source */
        Source: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "note" | "link" | "file";
            /** Name */
            name: string;
            /** Text */
            text: string;
            /** Url */
            url?: string | null;
            /** Createdat */
            createdAt: string;
        };
        /** SourceNote */
        "SourceNote-Input": {
            /** Sourceid */
            sourceId: string;
            /** Text */
            text: string;
            /** Verified */
            verified: boolean;
            /** Failurereason */
            failureReason?: ("content_unavailable" | "source_unverified") | null;
        };
        /** SourceNote */
        "SourceNote-Output": {
            /** Sourceid */
            sourceId: string;
            /** Text */
            text: string;
            /** Verified */
            verified: boolean;
            /** Failurereason */
            failureReason?: ("content_unavailable" | "source_unverified") | null;
        };
        /** SpellDiagnostic */
        SpellDiagnostic: {
            /** Lineid */
            lineId: string;
            /** Quote */
            quote: string;
            /** Replacement */
            replacement: string;
            /** Reason */
            reason: string;
        };
        /** StoredRetryRequest */
        StoredRetryRequest: {
            /**
             * Modulekey
             * @enum {string}
             */
            moduleKey: "spellCheck" | "companyContextAnalysis" | "jobPostingAnalysis" | "finalReview";
            record?: components["schemas"]["ReviewRecord"] | null;
            /** Reviewid */
            reviewId?: string | null;
        };
        /** SuggestionDTO */
        SuggestionDTO: {
            /** Id */
            id?: string | null;
            /** Previoussuggestionid */
            previousSuggestionId?: string | null;
            "\uC218\uC815\uD3EC\uC778\uD2B8\uC704\uCE58": components["schemas"]["SuggestionLocation"];
            /**
             * 수정성격
             * @enum {string}
             */
            "\uC218\uC815\uC131\uACA9": "맞춤법" | "사실성" | "근거" | "직무 관련성" | "회사 맥락" | "뉘앙스" | "가독성" | "기밀";
            /** 검토출처 */
            "\uAC80\uD1A0\uCD9C\uCC98": ("기본 검토" | "채용 공고" | "회사 자료")[];
            /** 검토자료근거 */
            "\uAC80\uD1A0\uC790\uB8CC\uADFC\uAC70": components["schemas"]["MaterialEvidence"][];
            /** 이유 및 제안 */
            "\uC774\uC720 \uBC0F \uC81C\uC548": string;
            /** 실제 수정 예시 */
            "\uC2E4\uC81C \uC218\uC815 \uC608\uC2DC": string;
        };
        /** SuggestionEntry */
        SuggestionEntry: {
            /** Id */
            id: string;
            /** Contextid */
            contextId: string;
            /** Reviewid */
            reviewId: string;
            /** Resumeversionid */
            resumeVersionId: string | null;
            content: components["schemas"]["SuggestionDTO"];
            /** Rating */
            rating: ("up" | "down") | null;
            /**
             * Decision
             * @enum {string}
             */
            decision: "open" | "resolve" | "skip";
            verification?: components["schemas"]["ResolutionCheck"] | null;
        };
        /** SuggestionFeedback */
        SuggestionFeedback: {
            /** Id */
            id: string;
            /** Contextid */
            contextId: string;
            /** Reviewid */
            reviewId: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "resolve" | "skip";
            /** Rating */
            rating?: ("up" | "down") | null;
            suggestion: components["schemas"]["SuggestionDTO"];
        };
        /** SuggestionLocation */
        SuggestionLocation: {
            /** Lineids */
            lineIds: string[];
            /** Quote */
            quote: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WritingMaterial */
        WritingMaterial: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Content */
            content: string;
            /**
             * Materialtype
             * @enum {string}
             */
            materialType: "company" | "jobPosting";
        };
        /** WritingResult */
        WritingResult: {
            /** Markdown */
            markdown: string;
            /** Summary */
            summary: string;
            /** Questions */
            questions: string[];
            /** Sourcenotes */
            sourceNotes: components["schemas"]["SourceNote-Output"][];
        };
        /** WritingResume */
        WritingResume: {
            /** Id */
            id: string;
            /** Text */
            text: string;
        };
        /** WritingInput */
        app__experience__api__WritingInput: {
            experience: components["schemas"]["ExperienceInput"];
            resume: components["schemas"]["ResumeInput"];
            /** Materials */
            materials: components["schemas"]["MaterialInput"][];
        };
        /** WritingInput */
        app__workspace__models__WritingInput: {
            experience: components["schemas"]["ExperienceSnapshot"];
            resume: components["schemas"]["WritingResume"];
            /** Materials */
            materials: components["schemas"]["WritingMaterial"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    validation_policy_api_resumes_validation_policy_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeValidationPolicy"];
                };
            };
        };
    };
    pdf_api_resumes_extract_pdf_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_pdf_api_resumes_extract_pdf_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractPageDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    image_api_resumes_extract_image_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_image_api_resumes_extract_image_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractPageDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    docx_api_resumes_extract_docx_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_docx_api_resumes_extract_docx_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractFlowDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    txt_api_resumes_extract_txt_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_txt_api_resumes_extract_txt_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractFlowDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    text_api_resumes_extract_text_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DirectTextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractFlowDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_page_api_reviews_page_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PageReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_flow_api_reviews_flow_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlowReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    result_api_reviews__run_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_reviews__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_reviews__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_api_reviews__run_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_api_reviews__run_id__record_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_stored_api_reviews_retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoredRetryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    release_api_reviews__run_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_materials_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaterialPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_experience_api_experiences_write_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["app__experience__api__WritingInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WritingResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    draft_experience_api_experiences_draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthoringInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WritingResult"];
                    "text/event-stream": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_metadata_api_experiences_metadata_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MetadataInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetadataResult"];
                    "text/event-stream": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    account_api_account_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    save_key_api_account_openai_key_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeyInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_key_api_account_openai_key_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    load_workspace_api_workspace_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    workspace_command_api_workspace_commands_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Command"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_local_workspace_api_workspace_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_status_api_workspace_import__import_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_file_api_files_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_api_files_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_file_api_files__file_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_unused_file_api_files__file_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backup_status_api_operations_backup_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupStatus"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
