import { createTestRouter } from "./test/router";
import { act, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { expect, it, vi } from "vitest";
import { App } from "./App";
import { IndexedDbWorkspaceRepository } from "./infrastructure/workspace/IndexedDbWorkspaceRepository";
import { resumeInput } from "./test/fixtures";

const policy = { maximumFileSizeBytes: { pdf: 20, image: 20, docx: 20, txt: 5 }, maximumDirectTextCharacters: 100 };
function deferred<T>() {
  let resolve!: (value: T) => void;
  let reject!: (error: Error) => void;
  const promise = new Promise<T>((done, fail) => { resolve = done; reject = fail; });
  return { promise, resolve, reject };
}
function setup(path = "/contexts/new", overrides = {}) {
  window.history.replaceState(null, "", path);
  const store = new IndexedDbWorkspaceRepository(`input-${crypto.randomUUID()}`);
  const services = { getValidationPolicy: vi.fn().mockResolvedValue(policy), extractText: vi.fn().mockResolvedValue(resumeInput().document), extractFile: vi.fn().mockResolvedValue({ kind: "flow", document: resumeInput().document }), ...overrides };
  render(<App router={createTestRouter()} store={store} services={services} />); return { store, services };
}
it("creates an isolated context only after extraction and explicit confirmation", async () => {
  const { store, services } = setup();
  await userEvent.type(await screen.findByLabelText("작업 공간 이름"), "프런트엔드 지원");
  await userEvent.click(screen.getByRole("tab", { name: "직접 입력" }));
  await userEvent.type(screen.getByLabelText("이력서 텍스트"), "경력 한 줄");
  await userEvent.click(screen.getByRole("button", { name: "작업 공간 만들기" }));
  expect((await store.load()).contexts).toHaveLength(0);
  await userEvent.click(await screen.findByRole("checkbox", { name: "원본과 비교해 검토에 사용할 수 있음을 확인했습니다." }));
  await userEvent.click(screen.getByRole("button", { name: "확인 후 저장" }));
  expect(await screen.findByRole("button", { name: "이력서 검토하기" })).toBeEnabled();
  expect(services.extractText).toHaveBeenCalledWith("경력 한 줄");
  expect((await store.load()).contexts).toHaveLength(1);
});
it("keeps the same preview after a failed save and retries without extracting again", async () => {
  const { store, services } = setup();
  const createContext = store.createContext.bind(store);
  vi.spyOn(store, "createContext").mockRejectedValueOnce(new Error("저장 실패")).mockImplementation(createContext);
  await userEvent.type(await screen.findByLabelText("작업 공간 이름"), "저장 재시도");
  await userEvent.upload(screen.getByLabelText("이력서 파일"), new File(["hello"], "resume.txt", { type: "text/plain" }));
  await userEvent.click(screen.getByRole("button", { name: "작업 공간 만들기" }));
  const dialog = await screen.findByRole("dialog", { name: "추출 내용 확인" });
  await userEvent.click(within(dialog).getByRole("checkbox"));
  await userEvent.click(within(dialog).getByRole("button", { name: "확인 후 저장" }));
  expect(await screen.findByRole("alert")).toHaveTextContent("저장 실패");
  expect(store.getSnapshot().contexts).toHaveLength(0);
  await userEvent.click(screen.getByRole("button", { name: "확인" }));
  expect(screen.getByRole("dialog", { name: "추출 내용 확인" })).toBe(dialog);
  expect(within(dialog).getByRole("checkbox")).toBeChecked();
  expect(within(dialog).getByRole("button", { name: "확인 후 저장" })).toBeEnabled();
  await userEvent.click(within(dialog).getByRole("button", { name: "확인 후 저장" }));
  await screen.findByRole("button", { name: "이력서 검토하기" });
  expect(services.extractFile).toHaveBeenCalledTimes(1);
  expect(store.getSnapshot().contexts).toHaveLength(1);
});
it("shows actual preparation, file conversion and persistence stages until saving finishes", async () => {
  const validation = deferred<typeof policy>();
  const extracted = deferred<{ kind: "flow"; document: ReturnType<typeof resumeInput>["document"] }>();
  const saving = deferred<void>();
  const { store, services } = setup("/contexts/new", { getValidationPolicy: () => validation.promise, extractFile: vi.fn(() => extracted.promise) });
  const createContext = store.createContext.bind(store);
  vi.spyOn(store, "createContext").mockImplementation(async (...args) => { await saving.promise; return createContext(...args); });
  await userEvent.type(await screen.findByLabelText("작업 공간 이름"), "진행 확인");
  await userEvent.upload(screen.getByLabelText("이력서 파일"), new File(["hello"], "resume.txt", { type: "text/plain" }));
  await userEvent.click(screen.getByRole("button", { name: "작업 공간 만들기" }));
  const dialog = await screen.findByRole("dialog", { name: "추출 내용 확인" });
  expect(within(dialog).getByText("입력 확인")).toHaveAttribute("aria-current", "step");
  expect(dialog.querySelector(".document-skeleton")).toBeInTheDocument();
  expect(screen.getByLabelText("이력서 파일")).toBeDisabled();
  fireEvent(dialog, new Event("cancel", { cancelable: true }));
  expect(dialog).toHaveAttribute("open");
  await act(async () => validation.resolve(policy));
  expect(within(dialog).getByText("문서 변환")).toHaveAttribute("aria-current", "step");
  expect(within(dialog).getByRole("status")).toHaveTextContent("이력서의 글자와 문서 구조를 읽고 있습니다.");
  expect(store.getSnapshot().contexts).toHaveLength(0);
  expect(services.extractFile).toHaveBeenCalledTimes(1);
  await act(async () => extracted.resolve({ kind: "flow", document: resumeInput().document }));
  expect(screen.getByRole("dialog", { name: "추출 내용 확인" })).toBe(dialog);
  expect(screen.getAllByRole("dialog")).toHaveLength(1);
  expect(dialog.querySelector(".document-skeleton")).not.toBeInTheDocument();
  expect(within(dialog).getByText("변환 완료")).toBeInTheDocument();
  expect(within(dialog).getByText("내용 확인", { exact: true })).toHaveAttribute("aria-current", "step");
  expect(within(dialog).getByRole("region", { name: "비교할 원문" })).toHaveTextContent("경력 한 줄");
  expect(store.getSnapshot().contexts).toHaveLength(0);
  await userEvent.click(within(dialog).getByRole("checkbox"));
  await userEvent.click(within(dialog).getByRole("button", { name: "확인 후 저장" }));
  expect(screen.getByRole("dialog", { name: "추출 내용 확인" })).toBe(dialog);
  expect(within(dialog).getByText("저장", { exact: true })).toHaveAttribute("aria-current", "step");
  expect(store.getSnapshot().contexts).toHaveLength(0);
  await act(async () => saving.resolve());
  await screen.findByRole("button", { name: "이력서 검토하기" });
  expect(screen.queryByRole("dialog", { name: "추출 내용 확인" })).not.toBeInTheDocument();
  expect(store.getSnapshot().contexts).toHaveLength(1);
});

it("removes the progress dialog after failure and retries with the selected file intact", async () => {
  const extracted = deferred<never>();
  const { store, services } = setup("/contexts/new", { extractFile: vi.fn().mockImplementationOnce(() => extracted.promise).mockResolvedValue({ kind: "flow", document: resumeInput().document }) });
  await userEvent.type(await screen.findByLabelText("작업 공간 이름"), "재시도");
  const file = new File(["hello"], "resume.txt", { type: "text/plain" });
  await userEvent.upload(screen.getByLabelText("이력서 파일"), file);
  await userEvent.click(screen.getByRole("button", { name: "작업 공간 만들기" }));
  await screen.findByRole("dialog", { name: "추출 내용 확인" });
  await act(async () => extracted.reject(new Error("변환 실패")));
  expect(await screen.findByRole("alert")).toHaveTextContent("변환 실패");
  expect(screen.queryByRole("dialog", { name: "추출 내용 확인" })).not.toBeInTheDocument();
  expect(screen.getByLabelText("이력서 파일")).toBeEnabled();
  expect(store.getSnapshot().contexts).toHaveLength(0);
  await userEvent.click(screen.getByRole("button", { name: "확인" }));
  await userEvent.click(screen.getByRole("button", { name: "작업 공간 만들기" }));
  await userEvent.click(await screen.findByRole("checkbox", { name: "원본과 비교해 검토에 사용할 수 있음을 확인했습니다." }));
  await userEvent.click(screen.getByRole("button", { name: "확인 후 저장" }));
  await screen.findByRole("button", { name: "이력서 검토하기" });
  expect(services.extractFile).toHaveBeenLastCalledWith(file, "txt");
});
it("rejects an oversized file before extraction", async () => {
  const { store, services } = setup();
  await userEvent.type(await screen.findByLabelText("작업 공간 이름"), "A");
  await userEvent.upload(screen.getByLabelText("이력서 파일"), new File(["123456"], "resume.txt", { type: "text/plain" }));
  await userEvent.click(screen.getByRole("button", { name: "작업 공간 만들기" }));
  expect(await screen.findByRole("alert")).toHaveTextContent("파일 크기");
  expect(services.extractFile).not.toHaveBeenCalled();
  expect((await store.load()).contexts).toEqual([]);
});

it("requires extraction confirmation before saving a suspect resume", async () => {
  const document = { ...resumeInput("확인할 문장").document, extraction: { status: "needs_review", confirmed: false, issues: [
    { stage: "assessment", code: "LOW_OCR_CONFIDENCE", message: "원본과 비교해 주세요.", lineIds: ["f-l1"], recovered: false },
  ] } };
  const extracted = deferred<typeof document>();
  const { store } = setup("/contexts/new", { extractText: vi.fn(() => extracted.promise) });
  await userEvent.type(await screen.findByLabelText("작업 공간 이름"), "확인 테스트");
  await userEvent.click(screen.getByRole("tab", { name: "직접 입력" }));
  await userEvent.type(screen.getByLabelText("이력서 텍스트"), "확인할 문장");
  await userEvent.click(screen.getByRole("button", { name: "작업 공간 만들기" }));
  const dialog = await screen.findByRole("dialog", { name: "추출 내용 확인" });
  await act(async () => extracted.resolve(document));
  expect(screen.getByRole("dialog", { name: "추출 내용 확인" })).toBe(dialog);
  expect(screen.getAllByRole("dialog")).toHaveLength(1);
  expect(screen.getByRole("button", { name: "확인 후 저장" })).toBeDisabled();
  expect((await store.load()).contexts).toHaveLength(0);
  await userEvent.click(screen.getByRole("checkbox", { name: "원본과 비교해 검토에 사용할 수 있음을 확인했습니다." }));
  await userEvent.click(screen.getByRole("button", { name: "확인 후 저장" }));
  await screen.findByRole("button", { name: "이력서 검토하기" });
  expect((await store.load()).resumeVersions[0].document?.extraction?.confirmed).toBe(true);
});
it("selects a dropped resume and saves it through the existing extraction flow", async () => {
  const { services } = setup();
  await userEvent.type(await screen.findByLabelText("작업 공간 이름"), "드롭 테스트");
  const input = screen.getByLabelText("이력서 파일");
  const area = input.closest("label")!;
  const file = new File(["hello"], "resume.txt", { type: "text/plain" });
  fireEvent.dragOver(input, { dataTransfer: { files: [file] } });
  expect(area).toHaveClass("is-dragging");
  fireEvent.drop(input, { dataTransfer: { files: [file] } });
  expect(area).not.toHaveClass("is-dragging");
  expect(screen.getByText("resume.txt")).toBeInTheDocument();
  await userEvent.click(screen.getByRole("button", { name: "작업 공간 만들기" }));
  await userEvent.click(await screen.findByRole("checkbox", { name: "원본과 비교해 검토에 사용할 수 있음을 확인했습니다." }));
  await userEvent.click(screen.getByRole("button", { name: "확인 후 저장" }));
  await screen.findByRole("button", { name: "이력서 검토하기" });
  expect(services.extractFile).toHaveBeenCalledWith(file, "txt");
});
it("previews, edits and explicitly saves a material", async () => {
  const { store } = setup("/materials");
  await userEvent.click(await screen.findByRole("button", { name: "새 자료 등록" }));
  expect(screen.getByRole("dialog", { name: "자료 미리보기" })).toHaveAttribute("open");
  expect(screen.getByLabelText("자료 제목")).toHaveFocus();
  await userEvent.type(screen.getByLabelText("자료 제목"), "공고 A");
  await userEvent.type(screen.getByLabelText("자료 입력"), "React 경험");
  await userEvent.click(screen.getByRole("button", { name: "추출 내용 확인" }));
  await screen.findByLabelText("추출 내용");
  expect((await store.load()).materials).toEqual([]);
  await userEvent.type(screen.getByLabelText("추출 내용"), "과 테스트 경험");
  await userEvent.click(screen.getByRole("button", { name: "자료 저장" }));
  await waitFor(async () => expect((await store.load()).materialVersions[0].content).toBe("React 경험과 테스트 경험"));
  expect(screen.queryByRole("dialog", { name: "자료 미리보기" })).not.toBeInTheDocument();
});
it("warns before abandoning an unsaved material draft", async () => {
  const confirm = vi.spyOn(window, "confirm").mockReturnValue(false);
  const { store } = setup("/materials");
  await userEvent.click(await screen.findByRole("button", { name: "새 자료 등록" }));
  await userEvent.type(screen.getByLabelText("자료 제목"), "작성 중");
  await userEvent.click(screen.getByRole("button", { name: "편집 취소" }));
  expect(confirm).toHaveBeenCalled();
  expect(screen.getByLabelText("자료 제목")).toHaveValue("작성 중");
  expect((await store.load()).materials).toEqual([]);
  fireEvent(screen.getByRole("dialog", { name: "자료 미리보기" }), new Event("cancel", { cancelable: true }));
  expect(screen.getByLabelText("자료 제목")).toHaveValue("작성 중");
  confirm.mockReturnValue(true);
  fireEvent(screen.getByRole("dialog", { name: "자료 미리보기" }), new Event("cancel", { cancelable: true }));
  expect(screen.queryByRole("dialog", { name: "자료 미리보기" })).not.toBeInTheDocument();
  confirm.mockRestore();
});

it("keeps a revision and the existing original when extraction fails", async () => {
  const store = new IndexedDbWorkspaceRepository(`revision-${crypto.randomUUID()}`);
  const id = await store.createContext("A", resumeInput());
  window.history.replaceState(null, "", `/contexts/${id}/upload`);
  const services = { getValidationPolicy: vi.fn().mockResolvedValue(policy), extractText: vi.fn().mockRejectedValue(new Error("변환 실패")) };
  render(<App router={createTestRouter()} store={store} services={services} />);
  await userEvent.click(await screen.findByRole("tab", { name: "직접 입력" }));
  await userEvent.type(screen.getByLabelText("이력서 텍스트"), "새 수정본");
  await userEvent.click(screen.getByRole("button", { name: "수정본 저장" }));
  expect(await screen.findByRole("alert")).toHaveTextContent("변환 실패");
  expect(screen.getByLabelText("이력서 텍스트")).toHaveValue("새 수정본");
  const state = await store.load();
  expect(state.resumeVersions).toHaveLength(1);
  expect(state.resumeVersions[0].original).toBe(resumeInput().original);
});
