import { createTestRouter } from "./test/router";
import { render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { expect, it, vi } from "vitest";
import { App } from "./App";
import { IndexedDbWorkspaceRepository } from "./infrastructure/workspace/IndexedDbWorkspaceRepository";
import { resumeInput, materialDraft } from "./test/fixtures";

it("selects shared library material read-only, detaches it, and preserves another context", async () => {
  const store = new IndexedDbWorkspaceRepository(`integration-${crypto.randomUUID()}`);
  const a = await store.createContext("지원 A", resumeInput());
  const b = await store.createContext("지원 B", resumeInput());
  const material = await store.saveMaterial(materialDraft(), undefined, b);
  const second = await store.saveMaterial({ ...materialDraft("회사 소개"), title: "회사 자료", materialType: "company" });
  window.history.replaceState(null, "", `/contexts/${a}`);
  render(<App router={createTestRouter()} store={store} services={{ getValidationPolicy: vi.fn().mockResolvedValue({ maximumFileSizeBytes: { pdf: 100, image: 100, docx: 100, txt: 100 }, maximumDirectTextCharacters: 100 }) }} />);
  await userEvent.click(await screen.findByRole("button", { name: /검토 자료/ }));
  const drawer = screen.getByRole("dialog", { name: "검토 자료" });
  await userEvent.click(within(drawer).getByRole("button", { name: "보관함에서 불러오기" }));
  let picker = screen.getByRole("dialog", { name: "보관함에서 불러오기" });
  expect(within(picker).getByRole("button", { name: "가져오기" })).toBeDisabled();
  await userEvent.click(within(picker).getByRole("checkbox", { name: "채용 자료" }));
  expect((await store.load()).contextMaterials).toHaveLength(1);
  await userEvent.click(within(picker).getByRole("button", { name: "취소" }));
  expect(screen.queryByRole("dialog", { name: "보관함에서 불러오기" })).not.toBeInTheDocument();
  await userEvent.click(within(drawer).getByRole("button", { name: "보관함에서 불러오기" }));
  picker = screen.getByRole("dialog", { name: "보관함에서 불러오기" });
  expect(within(picker).getByRole("checkbox", { name: "채용 자료" })).not.toBeChecked();
  await userEvent.click(within(picker).getByRole("checkbox", { name: "채용 자료" }));
  await userEvent.click(within(picker).getByRole("checkbox", { name: "회사 자료" }));
  await userEvent.click(within(picker).getByRole("button", { name: "가져오기" }));
  await waitFor(() => expect(within(drawer).getByText("React 경험")).toBeInTheDocument());
  expect((await store.load()).contextMaterials).toHaveLength(3);
  await userEvent.click(within(drawer).getByRole("button", { name: "보관함에서 불러오기" }));
  picker = screen.getByRole("dialog", { name: "보관함에서 불러오기" });
  expect(within(picker).getByRole("checkbox", { name: "채용 자료" })).toBeDisabled();
  await userEvent.click(within(picker).getByRole("button", { name: "취소" }));
  expect(within(drawer).queryByRole("textbox")).not.toBeInTheDocument();
  await userEvent.click(within(drawer).getByRole("button", { name: "채용 자료 연결 해제" }));
  await waitFor(() => expect(within(drawer).getByRole("button", { name: "회사 자료 연결 해제" })).toBeEnabled());
  await userEvent.click(within(drawer).getByRole("button", { name: "회사 자료 연결 해제" }));
  await waitFor(async () => expect((await store.load()).contextMaterials).toEqual([expect.objectContaining({ contextId: b, materialId: material })]));
  await expect(store.attachMaterial(a, [second, "missing-material"])).rejects.toThrow();
  expect((await store.load()).contextMaterials).toHaveLength(1);
});
